#!/bin/bash
#
# Copyright 2009-2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# vapprun needs access to vmrun, mkisofs, and vmware-vdiskmanager commands
# On Linux, they are all in /usr/bin and should already be in the path.
# On Mac OS X, they are installed as part of VMware Fusion

PRG="$0"
if [ -L "$PRG" ]; then
   PRG=`readlink "$PRG"`
fi
INSTALLDIR=`dirname $PRG`

export OS_TYPE=`uname`

if [ "$OS_TYPE" = "Darwin" ]; then
    PATH=/Library/Application\ Support/VMware\ Fusion:$PATH
fi

PYTHON_CMD=python
if [ -n "$PYTHON_HOME" ]; then
   PYTHON_CMD=$PYTHON_HOME/python
fi

$PYTHON_CMD $INSTALLDIR/src/vapprun.py $*
